name: Build and analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        uses: actions/checkout@v4

      # 1) SONARCLOUD
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      # 2) SETUP NODE
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      # 3) Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./todo.frontend
        run: npm install

      # 4) Build frontend (necesario para Sonar)
      - name: Build frontend
        working-directory: ./todo.frontend
        run: npm run build

      # 5) Run Cypress tests (arranca server + test)
      - name: Run Cypress tests
        working-directory: ./todo.frontend
        run: npm run ci:test

      # 6) Generate coverage report
      - name: Generate coverage report
        working-directory: ./todo.frontend
        run: npm run coverage:report

      # 7) Move coverage to root so SonarCloud lo encuentre
      - name: Move coverage to root
        run: mv todo.frontend/coverage/lcov.info lcov.info
