name: Build and analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    # ----- SONARCLOUD -----
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io

    # ----- SETUP NODE -----
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    # ----- INSTALL FRONTEND -----
    - name: Install frontend dependencies
      working-directory: ./todo.frontend
      run: npm install

    # ----- BUILD FRONTEND -----
    - name: Build frontend
      working-directory: ./todo.frontend
      run: npm run build

    # ----- RUN CYPRESS WITH SERVER -----
    - name: Run Cypress tests
      working-directory: ./todo.frontend
      run: npm run cy:ci

    # ----- GENERATE COVERAGE -----
    - name: Generate coverage report
      working-directory: ./todo.frontend
      run: npm run coverage:report

    # ----- MOVE COVERAGE TO ROOT FOR SONAR -----
    - name: Move coverage to root
      run: mv todo.frontend/coverage/lcov.info lcov.info
